### ISSUE TITLE
Add support for React Native

### ISSUE THREAD

**Issue by elmcapp** [orchetect/MIDIKit#126]
It would be nice if you could add support for React native (iOS and react native for macOS ). 
MidiKit React Native Bridge for iOS and macOS

**Comment by orchetect** [comment]
I have not used React Native. Was #91 not enough?

**Comment by elmcapp** [comment]
Yes. I forgot about that post, sorry. I did create a React Native bridge just have to keep it updated. Sorry again for reposting. If you don't know I can later share code on how to use with React Native

**Comment by orchetect** [comment]
Sure, if you have some suggestions to make it easier to use with RN let me know.
