### ISSUE TITLE
MidiKit Bluetooth Simple class example request

### ISSUE THREAD

**Issue by elmcapp** [orchetect/MIDIKit#127]
I wrote a MidiKit React Native Bridge module. Is there any licence doc that I should include so that I can give credit to you for MidiKit.

Also is there a way you could possibly provide a simple class on how to use MidiKit with bluetooth. I see that you provided an example project however I really don't understand how bluetooth works. If you could provide a simple class to show how to use MidiKit with bluetooth It could help me understand how to create a React Native bridge to  support bluetooth

Idea would be to have an example like this link 
https://github.com/orchetect/MIDIKit/wiki/Simple-MIDI-Listener-Class-Example

**Comment by orchetect** [comment]
> I wrote a MidiKit React Native Bridge module. Is there any licence doc that I should include so that I can give credit to you for MidiKit.

Not sure what you mean. Is this something that will be published somewhere other than this repo, or pushed to some package library/tracker?

I would love to know more how these bridges work or see an example of it done. Does it import all of MIDIKit's API or is there more work needed to adapt it?

> Also is there a way you could possibly provide a simple class on how to use MidiKit with bluetooth. I see that you provided an example project however I really don't understand how bluetooth works. If you could provide a simple class to show how to use MidiKit with bluetooth It could help me understand how to create a React Native bridge to support bluetooth

The code in the Bluetooth example project is used to set up connections. After that, Bluetooth MIDI endpoints show up along with any other endpoints in the system and aren't really differentiated. So there isn't really a way to demonstrate how that works unless you have a Bluetooth MIDI device to test it with.

**Comment by orchetect** [comment]
FWIW I just pushed some updates to the BluetoothMIDI example projects to `main` branch. They now successfully build, connect to devices, log all received events to the console, and can send a test MIDI message to the connected device.
