### ISSUE TITLE
AddInputConnection stopped working

### ISSUE THREAD

**Issue by elmcapp** [orchetect/MIDIKit#146]
### Please Confirm

- [X] I have reviewed the **[MIDIKit Documentation](https://orchetect.github.io/MIDIKit)** which contains descriptive guides and extensive API reference
- [X] I have searched **[Issues](https://github.com/orchetect/MIDIKit/issues?q=is%3Aissue)** and **[Discussions](https://github.com/orchetect/MIDIKit/discussions)** to see if the same question has already been asked

### macOS Version(s) Used to Build

macOS 12 Monterey

### Xcode Version(s)

Xcode 13.4.1

### Description

I am having issues with getting addInputConnection to work with latest version of MidiKit. Looks as this worked in version 0.60 but not with latest version

````
public let midiManager = MIDIManager(
                     clientName: "ELMC Midi Deck",
                     model: "Midi Deck",
                     manufacturer: "ELMC")

let connection = "inputConnection"

        do {
           try midiManager.addInputConnection(
            toOutputs: [.uniqueID(88734594)],
             tag: connection,
             mode: .definedEndpoints,
             filter: .default(),
             receiver: .events { [weak self] events in
                 events.forEach { self?.handleMIDI($0) }
                             }
           )

        } catch {
         print("error setting up connection")
        }
````

**Comment by elmcapp** [comment]
The issue is fixed. Sorry looks as it was an update in the ```receiver``` function I needed to make

**Comment by orchetect** [comment]
```swift
toOutputs: [.uniqueID(88734594)],
```

Just a tip: this should never be an integer literal. Core MIDI assigns these ID numbers randomly and while they should remain stable for a while, they can change at any time. This ID should be retrieved from your persistent storage (UserDefaults perhaps) and then re-stored whenever it potentially changes.
