### ISSUE TITLE
SwiftUI preview error when I include the MIDIKIT package

### ISSUE THREAD

**Issue by amrmarzouk** [orchetect/MIDIKit#147]
### Please Confirm

- [X] I have reviewed the **[MIDIKit Documentation](https://orchetect.github.io/MIDIKit)** which contains descriptive guides and extensive API reference
- [X] I have searched **[Issues](https://github.com/orchetect/MIDIKit/issues?q=is%3Aissue)** and **[Discussions](https://github.com/orchetect/MIDIKit/discussions)** to see if the same question has already been asked

### macOS Version(s) Used to Build

macOS 12 Monterey

### Xcode Version(s)

Xcode 14

### Description

I tried finding a solution to this but couldn't. I hope it is not a silly one !

Once I include the swift package, SwiftUI Preview stops working. I attached a screenshot and the diagnostic error message below.
Thanks

XCode Version 14.0.1 (14A400)

```HumanReadableSwiftError
SettingsError: noExecutablePath(<IDESwiftPackageStaticLibraryProductBuildable:ObjectIdentifier(0x0000600013c4c0f0):'MIDIKit'>)```

**Comment by amrmarzouk** [comment]
<img width="479" alt="Screenshot 2022-11-17 at 10 03 32 AM" src="https://user-images.githubusercontent.com/184647/202530382-e398a8ca-a7f3-4a73-89b6-4567c54e0030.png">

**Comment by orchetect** [comment]
It’s an Xcode bug that affects many libraries.
