### ISSUE TITLE
Broken link in docs for Event Filters

### ISSUE THREAD

**Issue by NaanProphet** [orchetect/MIDIKit#166]
### Please Confirm

- [X] I have reviewed the **[MIDIKit Documentation](https://orchetect.github.io/MIDIKit)** which contains descriptive guides and extensive API reference
- [X] I have searched **[Issues](https://github.com/orchetect/MIDIKit/issues?q=is%3Aissue)** and **[Discussions](https://github.com/orchetect/MIDIKit/discussions)** to see if the same question has already been asked

### macOS Version(s) Used to Build

macOS 13 Ventura

### Xcode Version(s)

Xcode 14

### Description

Hi, I found a small broken link on this page:
https://orchetect.github.io/MIDIKit/documentation/midikit/midimanager-creating-ports

There is a link for `Event Filters` that routes to the following broken URL:
https://orchetect.github.io/MIDIKit/documentation/midikit/midikit-getting-started/Event-Filters

### Crash Logs, Screenshots or Other Attachments (if applicable)

<img width="1376" alt="image" src="https://user-images.githubusercontent.com/2568736/219963353-a8f7094d-5505-4313-a603-9bed75826d97.png">

**Comment by orchetect** [comment]
Thanks for the report. That will be fixed on next docs push.

**Comment by orchetect** [comment]
Fixed now.

**Comment by NaanProphet** [comment]
Thanks!
