### ISSUE TITLE
MIDIEventLogger example In Advanced Examples folder won't build

### ISSUE THREAD

**Issue by fracturedsoftware** [orchetect/MIDIKit#169]
### Please Confirm

- [X] I have reviewed the **[MIDIKit Documentation](https://orchetect.github.io/MIDIKit)** which contains descriptive guides and extensive API reference
- [X] I have searched **[Issues](https://github.com/orchetect/MIDIKit/issues?q=is%3Aissue)** and **[Discussions](https://github.com/orchetect/MIDIKit/discussions)** to see if the same question has already been asked

### macOS Version(s) Used to Build

macOS 13 Ventura

### Xcode Version(s)

Xcode 14

### Description

Getting quite a few :
'Call can throw, but it is not marked with 'try' and the error is not handled'
error messages in SendMIDIEventsSystemExclusiveView at:

Button { sendEvent(.sysEx7(  <- 'Call can throw, but it is not marked with 'try' and the error is not handled'

Also 'Value of type 'Int' has no member 'hexString'' errors:
let groupNumHex = $0.hexString(padTo: 1, prefix: true) <- 'Value of type 'Int' has no member 'hexString'

hth

**Comment by orchetect** [comment]
That doesn't seem right. It builds fine in CI and locally on my system.

Is this the head of main branch, or a release commit?

**Comment by fracturedsoftware** [comment]
I just downloaded MidiKit as a zip file and built locally. The early projects I built worked fine but several of the advanced projects don't build. I just selected Code ->Download zip from https://github.com/orchetect/MIDIKit. The default branch 'main' was selected.

I just retried downloading the project via Github desktop and a quick test shows the same errors.

hth,

Peter

**Comment by orchetect** [comment]
I just tried the same and everything builds fine. Not really sure what to suggest. It sounds like something is out of date. What's your OS and Xcode version? What version of MIDIKit do you see appear in Xcode's navigator when the projects open?

**Comment by orchetect** [comment]
Oh sorry, saw you're on Ventura with Xcode 14. Maybe quit Xcode and nuke the DerivedData folder?

Those errors sound like you somehow are downloading an older version of MIDIKit but the demo projects are pulling a newer version of MIDIKit as a dependency.

**Comment by orchetect** [comment]
Also try Update to Latest Package Versions in Xcode. It should be puling version 0.8.4.

**Comment by fracturedsoftware** [comment]
Hmm,

I did most of that before, but did it again just to make sure. Same problem. I updated all packages and cleared package caches and am indeed getting MIDIKit 0.8.4 + OTCore 1.4.9 + TimecodeKit 1.6.9.
<img width="1823" alt="Screenshot 2023-03-03 at 4 33 21 pm" src="https://user-images.githubusercontent.com/35247994/222639613-1db4fb49-5f86-43f8-9d71-8b09a227647c.png">

**Comment by orchetect** [comment]
Looking at the file structure, that's literally not what the project looks like now. Somehow you're downloading an old version of the repo.

**Comment by fracturedsoftware** [comment]
Ah, OK will experiment more. I only looked at MidiKit yesterday so haven't been doing anything strange. If it helps, this is the page I am downloading from:

<img width="1823" alt="Screenshot 2023-03-03 at 4 33 21 pm" src="https://user-images.githubusercontent.com/35247994/222640633-75873d27-31bf-4534-ab26-3fc79203ebd1.png">

**Comment by fracturedsoftware** [comment]
Sorry wrong screenshot:

<img width="1731" alt="Screenshot 2023-03-03 at 4 39 25 pm" src="https://user-images.githubusercontent.com/35247994/222640788-e6aaa56b-af4f-460e-90fe-0a4b84cfdb34.png">

**Comment by orchetect** [comment]
Try downloading from there. This is the zip link that GitHub gives when clicking on the green Code button and selecting zip file:

https://github.com/orchetect/MIDIKit/archive/refs/heads/main.zip

Downloading that, it builds fine for me and is the latest commit.

**Comment by fracturedsoftware** [comment]
Ok - it works

I just redownloaded your latest update from a few minutes ago. The project structure is indeed quite different. Not sure what happened but it seems to work fine now.

Thanks,

**Comment by orchetect** [comment]
My only guess is somehow you previously downloaded an older commit in the repo or downloaded from someone's fork that wasn't up to date?

Cheers

**Comment by fracturedsoftware** [comment]
Yeah - maybe. Weirdly, the project that I downloaded via GitHub desktop that I mentioned before does work now as well.

All is well and thanks

**Comment by fracturedsoftware** [comment]
Yeah - maybe. Weirdly, the project that I downloaded via GitHub desktop that I mentioned before does work now as well.

All is well and thanks
