### ISSUE TITLE
MTCVideoPlayer project fails to build

### ISSUE THREAD

**Issue by Treata11** [orchetect/MIDIKit#193]
### Please Confirm

- [X] I have reviewed the **[MIDIKit Documentation](https://orchetect.github.io/MIDIKit)** which contains descriptive guides and extensive API reference
- [X] I have searched **[Issues](https://github.com/orchetect/MIDIKit/issues?q=is%3Aissue)** and **[Discussions](https://github.com/orchetect/MIDIKit/discussions)** to see if the same question has already been asked

### macOS Version(s) Used to Build

macOS 14 Sonoma

### Xcode Version(s)

Xcode 15

#### MTCVideoPlayer fails to build.

The first issue deals with resolving the dependencies that can be handled pretty easily ...
But when dependencies are included to the project, You'll see errs in `EditableTimecode.swift` & `AVPlayer.swift` files that are probably caused by the changes and deprecations in newer releases of packages.

**Comment by orchetect** [comment]
Thanks for the heads-up. That example project actually shouldn't be there, it's a WIP and was pushed to main by accident.
