### ISSUE TITLE
Docs: "MIDI.File" typo?

### ISSUE THREAD

**Issue by mistydemeo** [orchetect/MIDIKit#210]
### Please Confirm

- [X] I have reviewed the **[MIDIKit Documentation](https://orchetect.github.io/MIDIKit)** which contains descriptive guides and extensive API reference
- [X] I have searched **[Issues](https://github.com/orchetect/MIDIKit/issues?q=is%3Aissue)** and **[Discussions](https://github.com/orchetect/MIDIKit/discussions)** to see if the same question has already been asked

### macOS Version(s) Used to Build

macOS 13 Ventura

### Xcode Version(s)

Xcode 14

### Description

One of the three examples of the SMF extension documents using `MIDI.File` in place of `MIDIFile`:

**Comment by orchetect** [comment]
`MIDI.File` was renamed to `MIDIFile` some time ago, but it's possible not all mentions in the docs were updated.

**Comment by mistydemeo** [comment]
OK, pushed a commit to my PR #209 to change it in the docs then.

**Comment by mistydemeo** [comment]
Fixed by #209.
