### ISSUE TITLE
ProgramChange midi1RawBytes()

### ISSUE THREAD

**Issue by kls943** [orchetect/MIDIKit#211]
### Please Confirm

- [X] I have reviewed the **[MIDIKit Documentation](https://orchetect.github.io/MIDIKit)** which contains descriptive guides and extensive API reference
- [X] I have searched **[Issues](https://github.com/orchetect/MIDIKit/issues?q=is%3Aissue)** and **[Discussions](https://github.com/orchetect/MIDIKit/discussions)** to see if the same question has already been asked

### macOS Version(s) Used to Build

macOS 13 Ventura

### Xcode Version(s)

Xcode 14

### Description

Line 152 in ProgramChange.swift (func midi1RawBytes() -> [UInt8]) codes the Bank Select LSB (CC 32) as 0x32. But CC 32 is decimal 32. Line 152 should read 0x20

**Comment by orchetect** [comment]
Nice catch. Not sure how that got through unit testing, but I've performed the fix and updated unit tests.
