### ISSUE TITLE
Stale utility methods in MIDIKit

### ISSUE THREAD

**Issue by ryanfrancesconi** [orchetect/MIDIKit#83]
<img width="1033" alt="image" src="https://user-images.githubusercontent.com/2917795/163827703-4d414c9c-c59c-4761-b611-0d6b20d9146d.png">

**Comment by orchetect** [comment]
I pushed an update to https://github.com/orchetect/MIDIKit/tree/dev that updates all the utility methods. If you can check that it works I can merge and release.

**Comment by ryanfrancesconi** [comment]
ok great, thanks! yes those look good now.

**Comment by ryanfrancesconi** [comment]
yes, making them internal is right

**Comment by ryanfrancesconi** [comment]
i think it's right to not have an OTCore dependency in MIDIKit.

**Comment by orchetect** [comment]
0.4.6 Released: https://github.com/orchetect/MIDIKit/releases/tag/0.4.6
