### ISSUE TITLE
How to added MidiKit to project

### ISSUE THREAD

**Issue by elmcapp** [orchetect/MIDIKit#90]
I like to know where do we add MidiKit to the project. Do we add it to where the project name: "midi_module"  or to the pods

<img width="1088" alt="Screen Shot 2022-06-02 at 11 28 59 PM" src="https://user-images.githubusercontent.com/64275658/171780753-e704b347-e927-49f1-a2d5-a44986a3f44f.png">

**Comment by orchetect** [comment]
If you need help with using Swift packages in Xcode, there are plenty of resources online.

Please use Issues for MIDIKit-specific bugs or features only.
